version: "3.8"
services:
  camera_bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        WITH_RTABMAP: "1"  # set "0" to skip rtabmap_ros
    image: camera_bot:jazzy
    container_name: camera_bot
    # Host network
    network_mode: host
    # Mount the repo
    volumes:
      - .:/ws/src/camera_bot:delegated
      - /tmp/.X11-unix:/tmp/.X11-unix  # GUI (Gazebo) on Linux/X11
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    # gpus: all
    devices:
      - /dev/dri:/dev/dri
    shm_size: "1g"
    ulimits:
      memlock: -1
      stack: 67108864
    entrypoint: ["/usr/bin/tini","--","/entrypoint.sh"]
    command: [ "bash" ]

